print('1'+'3')
print('oie')
print(1+3)
print('1+3')
print('ola',5, '"ola+5" nao da certo,"olá,5" é o certo')
nome=input('qual seu nome?')
idade=input('quantos anos voce tem?')
peso=input('qual o seu peso?')
print ( 'olá,{}. Você tem {} anos,e pesa {} kg, certo?' .format(nome,idade,peso))
